

image: mcr.microsoft.com/dotnet/sdk:6.0  # Specify the .NET SDK version

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - dotnetcore
        script:
          - dotnet restore
          - dotnet build
          - dotnet test
